//! Scans `src/services/` at compile time and generates, into `OUT_DIR/services_gen.rs`:
//!
//!   1. a `pub mod <name>;` declaration for every service file found, and
//!   2. a `build_all()` function that calls each service's `descriptor(ctx)` to assemble the
//!      full list of `(ServiceMeta, Box<dyn ErasedService>)` entries the runtime registry needs.
//!
//! This is the single place that turns "a new file exists in `src/services/`" into "the binary
//! knows about it." Nothing else in the crate is touched to add, rename, or remove a service —
//! see the `descriptor()` convention used throughout `src/services/*.rs`.
//!
//! Deliberately filesystem-only: this script never parses Rust source. Anything it can't infer
//! from a filename it leaves for `rustc` to type-check via the fixed `descriptor()` signature,
//! so a service that forgets to implement it fails the build with an ordinary, precise
//! compiler error rather than a wrong codegen match.

use std::fmt::Write as _;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=src/services");

    let services_dir = Path::new("src/services");

    let mut names: Vec<String> = fs::read_dir(services_dir)
        .expect("src/services must exist")
        .filter_map(Result::ok)
        .filter_map(|entry| {
            let path = entry.path();
            let is_rs_file = path.is_file() && path.extension().is_some_and(|ext| ext == "rs");
            if !is_rs_file {
                return None;
            }
            path.file_stem()
                .and_then(|stem| stem.to_str())
                .map(str::to_owned)
        })
        .collect();

    // Sort for a deterministic, reviewable module order. Actual *display* order is controlled
    // separately by each service's `ServiceMeta::sort_order` field (see `core::registry`), so
    // renaming a file never reshuffles the CLI's output.
    names.sort();

    assert!(
        !names.is_empty(),
        "src/services must contain at least one service module"
    );

    let manifest_dir =
        std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is set by cargo");

    // An explicit `#[path = ...]` is required here (rather than a bare `pub mod <name>;`).
    // Once this generated file is pulled in via `include!`, rustc resolves any *implicit*
    // module file for `<name>` relative to OUT_DIR (where this generated file physically
    // lives), not relative to `src/services/`. The explicit path makes the real location
    // unambiguous regardless of where the `mod` item is textually assembled from.
    //
    // Built via `fold` + `write!` into one growing `String` rather than
    // `.map(|n| format!(...)).collect::<String>()`: the latter allocates and immediately
    // discards a fresh `String` per iteration only to concatenate it into the final one, which
    // is exactly what `clippy::format_collect` flags. `write!` into an accumulator allocates
    // once (amortized) for the whole list.
    let mod_decls = names.iter().fold(String::new(), |mut acc, name| {
        writeln!(
            acc,
            "#[path = \"{manifest_dir}/src/services/{name}.rs\"]\npub mod {name};"
        )
        .expect("writing to a String cannot fail");
        acc
    });

    let descriptor_calls = names.iter().fold(String::new(), |mut acc, name| {
        writeln!(acc, "        {name}::descriptor(ctx),").expect("writing to a String cannot fail");
        acc
    });

    let generated = format!(
        "// @generated by build.rs from the contents of src/services/ — do not edit by hand.\n\
         \n\
         {mod_decls}\n\
         /// Constructs one registry entry per service module discovered under `src/services/`.\n\
         pub fn build_all(\n    \
             ctx: &crate::core::context::ServiceContext,\n\
         ) -> Vec<(crate::core::meta::ServiceMeta, Box<dyn crate::core::erased::ErasedService>)> {{\n    \
             vec![\n{descriptor_calls}    ]\n\
         }}\n"
    );

    let out_path = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR is set by cargo"))
        .join("services_gen.rs");

    fs::write(&out_path, generated).expect("failed to write generated services module");
}
