// The `mod` declarations for every discovered service, plus `build_all()`, are generated by
// `build.rs` from a directory listing of `src/services`
//
//Nothing in this file — or anywhere else in the crate — needs to change when a service is added,
// renamed, or removed: the next build simply picks up the new file via the generated `include!`
// statement below
include!(concat!(env!("OUT_DIR"), "/services_gen.rs"));

use crate::RenderedRow;
use crate::core::error::AppError;

/// `prelude` re-exports the types shared across all service modules, eliminating duplicate
/// `use` statements in each service file
///
/// This module intentionally lives here rather than as a file under `src/services`, so that
/// `build.rs`'s directory scan of `src/services` never has to special-case it as "not a real
/// service" — every `.rs` file under that directory is a service... full stop
pub mod prelude {
    pub use super::Service;
    pub use crate::core::context::ServiceContext;
    pub use crate::core::erased::ErasedService;
    pub use crate::core::error::AppError;
    pub use crate::core::meta::ServiceMeta;
    pub use crate::presentation::format::{RenderedRow, Threshold};
}

/// `Service` is the common interface implemented by every system information service
pub trait Service {
    type Data;

    /// `collect()` reads raw system data and returns it
    ///
    fn collect(&self) -> Result<Self::Data, AppError>;

    /// `render()` formats and returns raw `data` into a display-ready `RenderedRow`
    ///
    fn render(&self, data: &Self::Data) -> Result<RenderedRow, AppError>;
}
